development:
  adapter: postgresql
  database: itutoru_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: itutoru_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: itutoru_production
  pool: 5
  timeout: 5000
